### ISSUE TITLE
Questions about enable_materialized_views and enable_transient_replication

### ISSUE THREAD

**Issue by ghost** [jeffharwell/cassandra-lucene#1]
Thanks for providing this useful container! I have a question about two cassandra configs: `enable_materialized_views` and `enable_transient_replication.` It seems the [official document](http://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html)
does not recommend to enable them in production but but they are set to be enabled in  `/etc/cassandra/cassandra.yaml`:

![image](https://user-images.githubusercontent.com/4555674/56547979-b8392100-6533-11e9-9347-aafdfaef4721.png)

Shall we disable them?
Thanks!

**Comment by jeffharwell** [comment]
Good catch! I'm glad the image has been useful to you.

It seems that Cassandra 3.11.3 (which is what the image is currently at) doesn't support the enable_transient_replication feature. When I drop that parameter into configuration.yaml Cassandra doesn't start:

> INFO  [main] 2019-04-24 19:17:10,030 YamlConfigurationLoader.java:89 - Configuration location: file:/etc/cassandra/cassandra.yaml
> Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: Invalid yaml. Please remove properties [enable_transient_replication] from your cassandra.yaml
> Invalid yaml. Please remove properties [enable_transient_replication] from your cassandra.yaml
> ERROR [main] 2019-04-24 19:17:10,867 CassandraDaemon.java:708 - Exception encountered during startup: Invalid yaml. Please remove properties [enable_transient_replication] from your cassandra.yaml

I did modify the default launch script (docker-entrypoint.sh) to go ahead and explicitly disable the "enable_materialized_views" unless the environmental variable CASSANDRA_ENABLE_MATERIALIZED_VIEWS="true" is passed to the container. In that case it will explicitly enable the feature in cassandra.yaml.

I need to do a bit more testing to make sure I'm not breaking anything else then I'll push up the new version and have docker hub refresh the image.

As an aside, do you have any pressing need to bump the Cassandra version up to 3.11.4? My deployment is really stable on 3.11.3 right now but the [delta from .3 to .4](https://gitbox.apache.org/repos/asf?p=cassandra.git;a=blob_plain;f=CHANGES.txt;hb=refs/tags/cassandra-3.11.4) looks pretty small but there are some significant bug fixes so I'd be willing to do that if it would be helpful.

**Comment by jeffharwell** [comment]
This should do it: Commit https://github.com/jeffharwell/cassandra-lucene/commit/4008d5eb473704c23297a41d83d438da81e09fff

**Comment by jeffharwell** [comment]
New version is up on [Dockerhub](https://cloud.docker.com/repository/docker/jeffharwell/cassandra-lucene/general) Version/Tag is 3.11.3.0v9.
